[package]
name = "array-map"
group = "john"
version = "0.1.0"
apiVersion = "0.1.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[[params]]
name = "input"
description = "input description"
